### ISSUE TITLE
[TR] Test report intel mac

### ISSUE THREAD

**Issue by mindej** [jcefmaven/jcefmaven#102]
Test report generated by JCefSampleApp
122.1.10

**OS (linux/windows/macosx)**
macosx

**Version/Flavor (e.g. Ubuntu 20.04, Windows 10, Big Sur)**
macOS 14.3.1 (14.3.1)

**Arch (amd64/i386/arm64/arm)**
amd64

**Report as working? (Y/N)**
N

**Did you test with the official sample app? (Y/N)**
Y

**Additional information**
Passed command line arguments: []

Error message: 

```
2024-04-04 18:02:57.024 java[59264:572871] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
Apr 04, 2024 6:02:57 PM me.friwi.jcefmaven.impl.progress.ConsoleProgressHandler handleProgress
INFO: LOCATING |> In progress...
Apr 04, 2024 6:02:57 PM me.friwi.jcefmaven.impl.progress.ConsoleProgressHandler handleProgress
INFO: INITIALIZING |> In progress...
Apr 04, 2024 6:02:57 PM me.friwi.jcefmaven.impl.progress.ConsoleProgressHandler handleProgress
INFO: INITIALIZED |> In progress...
[0404/180257.422798:WARNING:resource_util.cc(94)] Please customize CefSettings.root_cache_path for your application. Use of the default value may lead to unintended process singleton behavior.
initialize on Thread[AWT-EventQueue-0,6,main] with library path .....integration/jcefsampleapp/build/jcef-bundle
Exception in thread "main" java.lang.IllegalAccessError: class org.cef.browser.mac.CefBrowserWindowMac (in unnamed module @0x62bd765) cannot access class sun.awt.AWTAccessor (in module java.desktop) because module java.desktop does not export sun.awt to unnamed module @0x62bd765
	at org.cef.browser.mac.CefBrowserWindowMac.getWindowHandle(CefBrowserWindowMac.java:27)
	at org.cef.browser.CefBrowserWr.getWindowHandle(CefBrowserWr.java:339)
	at org.cef.browser.CefBrowserWr.access$600(CefBrowserWr.java:50)
	at org.cef.browser.CefBrowserWr$3.addNotify(CefBrowserWr.java:234)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at java.desktop/javax.swing.JRootPane.addNotify(JRootPane.java:726)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/java.awt.Window.addNotify(Window.java:791)
	at java.desktop/java.awt.Frame.addNotify(Frame.java:495)
	at java.desktop/java.awt.Window.pack(Window.java:829)
	at me.friwi.jcefsampleapp.MainFrame.<init>(MainFrame.java:174)
	at me.friwi.jcefsampleapp.MainFrame.main(MainFrame.java:198)
```

java version:

```
java --version
openjdk 21.0.2 2024-01-16
OpenJDK Runtime Environment Homebrew (build 21.0.2)
OpenJDK 64-Bit Server VM Homebrew (build 21.0.2, mixed mode, sharing)
```

**Comment by mindej** [comment]
Works as expected i just had to add JMV options:

```
--add-opens java.desktop/sun.awt=ALL-UNNAMED
--add-opens java.desktop/sun.lwawt=ALL-UNNAMED
--add-opens java.desktop/sun.lwawt.macosx=ALL-UNNAMED
```

**Comment by mindej** [comment]
Works as expected i just had to add JMV options:

```
--add-opens java.desktop/sun.awt=ALL-UNNAMED
--add-opens java.desktop/sun.lwawt=ALL-UNNAMED
--add-opens java.desktop/sun.lwawt.macosx=ALL-UNNAMED
```
