### ISSUE TITLE
[BUG] ...Exception in thread "main" java.lang.UnsatisfiedLinkError:

### ISSUE THREAD

**Issue by hteste** [jcefmaven/jcefmaven#106]
For Version 122.1.10 ，JDK1.8  32bit
Exception in thread "main" java.lang.UnsatisfiedLinkError: D:\java_works\eclipse-workspace\test\chrome_122\chrome_elf.dll:  
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at me.friwi.jcefmaven.impl.step.init.CefInitializer.initialize(CefInitializer.java:52)
	at me.friwi.jcefmaven.CefAppBuilder.build(CefAppBuilder.java:308)
	at cn.haoe.xb.jcef.XbBrownserTools.init(XbBrownserTools.java:246)
	at cn.haoe.xb.XbMainFrame.<init>(XbMainFrame.java:114)
	at cn.haoe.xb.XbMainFrame.main(XbMainFrame.java:460)
\chrome_elf.dll: 找不到指定的程序\chrome_elf.dll: 找不到指定的程序\chrome_elf.dll: 找不到指定的程序

**Comment by FriwiDev** [comment]
Please post your code or with what you tested

**Comment by ManOnSaturn** [comment]
> For Version 122.1.10 ，JDK1.8 32bit

@hteste This seems to be a Java-version problem. Are you using Java 8 or later?

**Comment by UnknownCoder56** [comment]
I have the same error

**Comment by KlemenDEV** [comment]
Duplicate of https://github.com/jcefmaven/jcefmaven/issues/121 ?
