### ISSUE TITLE
[NEED HELP] Help Needed with NoClassDefFoundError:

### ISSUE THREAD

**Issue by Zyroxlp** [jcefmaven/jcefmaven#116]
Hey i am trying to get this in to a mincraft 1.12.2 Mod with gradle

I pastet in the     implementation 'me.friwi:jcefmaven:127.3.1' in the build.gradle
![image](https://github.com/user-attachments/assets/2a48e39d-f72b-416a-a545-1b8d7b3c3f5d)

and put the jcefmaven-127.3.1.jar in the lib folder.
![image](https://github.com/user-attachments/assets/b17a1559-a968-429a-b6de-31ce10320174)

Intellij IDEA i can code with it but as soon as i want to launch Minecraft with the builded mod it does not work

>java.lang.NoClassDefFoundError: me/friwi/jcefmaven/MavenCefAppHandlerAdapter
[B#895]  	at java.lang.Class.forName0(Native Method)
[B#895]  	at java.lang.Class.forName(Class.java:348)
[B#895]  	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
[B#895]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#895]  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[B#895]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[B#895]  	at java.lang.reflect.Method.invoke(Method.java:497)
[B#895]  	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[B#895]  	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[B#895]  	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[B#895]  	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[B#895]  	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[B#895]  	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[B#895]  	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[B#895]  	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[B#895]  	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[B#895]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#895]  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[B#895]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[B#895]  	at java.lang.reflect.Method.invoke(Method.java:497)
[B#895]  	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[B#895]  	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[B#895]  	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[B#895]  	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[B#895]  	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[B#895]  	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[B#895]  	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[B#895]  	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[B#895]  	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
[B#895]  	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
[B#895]  	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
[B#895]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
[B#895]  	at net.minecraft.client.main.Main.main(SourceFile:123)
[B#895]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#895]  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[B#895]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[B#895]  	at java.lang.reflect.Method.invoke(Method.java:497)
[B#895]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#895]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[B#895]  Caused by: java.lang.ClassNotFoundException: me.friwi.jcefmaven.MavenCefAppHandlerAdapter
[B#895]  	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[B#895]  	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[B#895]  	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[B#895]  	... 39 more
[B#895]  Caused by: java.lang.NoClassDefFoundError: org/cef/handler/CefAppHandlerAdapter
[B#895]  	at java.lang.ClassLoader.defineClass1(Native Method)
[B#895]  	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[B#895]  	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[B#895]  	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[B#895]  	... 41 more
[B#895]  Caused by: java.lang.ClassNotFoundException: org.cef.handler.CefAppHandlerAdapter
[B#895]  	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[B#895]  	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[B#895]  	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[B#895]  	... 45 more

I used the code of the Mainframe in [Sampleapp ](https://github.com/jcefmaven/jcefsampleapp)

i hope someone can help me

**Comment by FriwiDev** [comment]
Why are you certain that this jar is ever loaded? The folder looks just like a random folder. You should most likely rather shade the jar within your minecraft mod. This is however off-topic on this repository.
