### ISSUE TITLE
macos Copy(Cmd+c) Paste(Cmd+v) do not work

### ISSUE THREAD

**Issue by supermoonie** [jcefmaven/jcefmaven#5]
```java
java.lang.UnsatisfiedLinkError: org.cef.browser.CefFrame_N.N_Copy(J)V
        at org.cef.browser.CefFrame_N.N_Copy(Native Method)
        at org.cef.browser.CefFrame_N.copy(CefFrame_N.java:137)
        at com.github.supermoonie.cef.core.Browser.lambda$hotKey$2(Browser.java:271)
        at java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2427)
        at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2319)
        at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2318)
        at java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2277)
        at java.awt.Component.dispatchEventImpl(Component.java:4785)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
        at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:835)
        at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1103)
        at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:974)
        at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:800)
        at java.awt.Component.dispatchEventImpl(Component.java:4760)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
        at java.awt.EventQueue$4.run(EventQueue.java:733)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by supermoonie** [comment]
Today i build java-cef by myself and copy my jar to `/path/jcef_app.app/Contents/Java/`, then launch it. copy and paste work. So is [jcef-build](https://github.com/jcefbuild/jcefbuild) not ok ?

**Comment by FriwiDev** [comment]
Possibly, or the versions mismatch.

**Comment by supermoonie** [comment]
> Possibly, or the versions mismatch.

The last macos version `cefBrowser.getFocusFrame()` no `copy()` & `paste()` 😂. Only build jcef by myself.
