### ISSUE TITLE
[ENH] Add option to change download mirrors/urls

### ISSUE THREAD

**Issue by dxslin** [jcefmaven/jcefmaven#52]
Exception in thread "AWT-EventQueue-0" javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2048)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2043)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2042)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1609)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
	at me.friwi.jcefmaven.impl.step.fetch.PackageDownloader.downloadNatives(PackageDownloader.java:56)
	at me.friwi.jcefmaven.CefAppBuilder.build(CefAppBuilder.java:192)

**Comment by dxslin** [comment]
PackageDownloader.java  line 56
I think getResponseCode() surround with try catch before uc.disconnect();

**Comment by FriwiDev** [comment]
@dxslin The potential requested URLs are on github.com and repo.maven.apache.org though. SSL verification should not fail on a correctly configured system. Even if I move the code around to not fail but try apache instead, its unlikely the second request would succeed. The exception currently thrown seems relatively descriptive for the issue - which is what you would expect from an api.

**Comment by dxslin** [comment]
@FriwiDev  The SSL verification promble maybe cause by [FastGithub](https://github.com/dotnetcore/FastGithub) although I had install the cacert/fastgithub.cer,  I use the it because the github.com is slowly and unstable in China. 
I can download jcef-bundle from repo.maven.apache.org, could you use it firstly?

**Comment by FriwiDev** [comment]
@dxslin Sorry for the late reply. I do not want to use repo.maven.apache.org for every user, as this is significantly slower for other users and also increases load on the oss repository - which I don't want to cause. But I can possibly implement functionality to create and set your own mirrors. I'm currently a bit on a tight schedule, but I will try to implement it in the upcoming two weeks. Does that sound like a good solution to you? :)

**Comment by dxslin** [comment]
@FriwiDev Thanks for reply, I think that is a good idea.

**Comment by FriwiDev** [comment]
@dxslin I just added the option to set the mirrors manually. Thank you for the suggestion :)

See release 100.0.14.4: https://github.com/jcefmaven/jcefmaven/releases/tag/100.0.14.4
