### ISSUE TITLE
Exception when starting on Ubuntu 20.04

### ISSUE THREAD

**Issue by ProjectBots** [jcefmaven/jcefmaven#6]
initialize on Thread[AWT-EventQueue-0,6,main] with library path /home/merlin/StreamRaidersBot/cef_bundle/84.3.8+gc8a556f+chromium-84.0.4147.105-linux64
Exception in thread "Thread-2" java.lang.UnsatisfiedLinkError: /tmp/jogamp_0000/file_cache/jln11480057672891235251/jln6780300819869535836/natives/linux-amd64/libnativewindow_awt.so: /usr/lib/jvm/jdk-16.0.1/lib/libjawt.so: version `SUNWprivate_1.1' not found (required by /tmp/jogamp_0000/file_cache/jln11480057672891235251/jln6780300819869535836/natives/linux-amd64/libnativewindow_awt.so)

for windows it is working perfectly fine

**Comment by ProjectBots** [comment]
Update: Debian buster

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:567)
    at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /home/pi/Downloads/StreamRaidersBot/natives/linux-armv6hf/libgluegen-rt.so
    at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2387)
    at java.base/java.lang.Runtime.load0(Runtime.java:746)
    at java.base/java.lang.System.load(System.java:1857)
    at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:624)
    at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:63)
    at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:106)
    at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:487)
    at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:421)
    at com.jogamp.common.os.Platform$1.run(Platform.java:317)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
    at com.jogamp.common.os.Platform.<clinit>(Platform.java:287)
    at org.cef.OSUtil.getJvmArch(OSUtil.java:28)
    at org.cef.JCefLoader.installAndLoadCef(JCefLoader.java:152)
    at org.cef.JCefLoader.installAndLoadCef(JCefLoader.java:102)
    at program.Browser.create(Browser.java:63)
    at program.StreamRaiders.main(StreamRaiders.java:177)
    ... 5 more```

**Comment by FriwiDev** [comment]
I just tested on Ubuntu 21 with OpenJDK 16 and it didnt print an error (apart from a null image url in the image loader). Try using open jdk instead of the oracle jdk, in case that is what you use. If the problem persists or you are already using openjdk, I can investigate this further in the upcoming days.

**Comment by ProjectBots** [comment]
I'll test it this weekend 😄

**Comment by ProjectBots** [comment]
seems fine

**Comment by ProjectBots** [comment]
nope its back again (or another issue?):
```
initialize on Thread[AWT-EventQueue-0,6,main] with library path /home/ubuntu/Downloads/StreamRaidersBot/cef_bundle/84.3.8+gc8a556f+chromium-84.0.4147.105-linux64
Exception in thread "Thread-2" java.lang.UnsatisfiedLinkError: /tmp/jogamp_0000/file_cache/jln3620590539883284778/jln6115113730885294356/natives/linux-amd64/libnativewindow_awt.so: /usr/java/openjdk/jdk-16.0.1/lib/libjawt.so: version `SUNWprivate_1.1' not found (required by /tmp/jogamp_0000/file_cache/jln3620590539883284778/jln6115113730885294356/natives/linux-amd64/libnativewindow_awt.so)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
	at java.base/java.lang.Runtime.load0(Runtime.java:746)
	at java.base/java.lang.System.load(System.java:1857)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:603)
	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:63)
	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:106)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:487)
	at jogamp.nativewindow.NWJNILibLoader.access$000(NWJNILibLoader.java:39)
	at jogamp.nativewindow.NWJNILibLoader$1.run(NWJNILibLoader.java:49)
	at jogamp.nativewindow.NWJNILibLoader$1.run(NWJNILibLoader.java:41)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at jogamp.nativewindow.NWJNILibLoader.loadNativeWindow(NWJNILibLoader.java:41)
	at jogamp.nativewindow.jawt.JAWTUtil.<clinit>(JAWTUtil.java:336)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at com.jogamp.nativewindow.NativeWindowFactory$3.run(NativeWindowFactory.java:344)
	at com.jogamp.nativewindow.NativeWindowFactory$3.run(NativeWindowFactory.java:340)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at com.jogamp.nativewindow.NativeWindowFactory.initSingleton(NativeWindowFactory.java:340)
	at com.jogamp.opengl.GLProfile.initProfilesForDefaultDevices(GLProfile.java:1721)
	at com.jogamp.opengl.GLProfile.access$000(GLProfile.java:80)
	at com.jogamp.opengl.GLProfile$1.run(GLProfile.java:230)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at com.jogamp.opengl.GLProfile.initSingleton(GLProfile.java:216)
	at com.jogamp.opengl.GLProfile.getProfileMap(GLProfile.java:2297)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1021)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1050)
	at com.jogamp.opengl.GLProfile.getMaxFixedFunc(GLProfile.java:803)
	at org.cef.browser.CefBrowserOsr.createGLCanvas(CefBrowserOsr.java:129)
	at org.cef.browser.CefBrowserOsr.<init>(CefBrowserOsr.java:87)
	at org.cef.browser.CefBrowserOsr.<init>(CefBrowserOsr.java:79)
	at org.cef.browser.CefBrowserFactory.create(CefBrowserFactory.java:15)
	at org.cef.CefClient.createBrowser(CefClient.java:139)
	at org.cef.CefClient.createBrowser(CefClient.java:132)
	at program.Browser.show(Browser.java:70)
	at program.MainFrame$5$1$1.run(MainFrame.java:319)
	at java.base/java.lang.Thread.run(Thread.java:831)
```
Also [https://friwi.me/jcef/maven/org/cef/jcef-main/](https://friwi.me/jcef/maven/org/cef/jcef-main/) is not reachable

Is it a Ubuntu 20.04 exclusive error?

(My implementation is [here](https://github.com/ProjectBots/StreamRaidersBot/blob/master/StreamRaiders/src/program/Browser.java))
(I am using openjdk)

**Comment by FriwiDev** [comment]
It seems to depend on the jdk you are using. This is not really an error in JCEF but in Jogamp. Other users are facing the same issues as you are: http://forum.jogamp.org/Oracle-Java-13-Linux-version-SUNWprivate-1-1-not-found-td4040172.html

Try searching for a compatible JDK. I have not found out yet, which JDK versions work and which dont. The integrated openjdk 16 of intellij seems to work without issues.
