### ISSUE TITLE
[TR] Test report - libcef.so: cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by S1artie** [jcefmaven/jcefmaven#70]
Test report generated by JCefSampleApp
**Tag**
110.0.25

**OS (linux/windows/macosx)**
linux

**Version/Flavor (e.g. Ubuntu 20.04, Windows 10, Big Sur)**
5.14.0-162.12.1.el9_1.0.2.aarch64

**Arch (amd64/i386/arm64/arm)**
arm64

**Report as working? (Y/N)**
N

**Did you test with the official sample app? (Y/N)**
Y

**Additional information**
The application fails to load:

Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/xxx/git/jcefsampleapp/jcef-bundle/libjcef.so: /home/xxx/git/jcefsampleapp/jcef-bundle/libcef.so: cannot allocate memory in static TLS block
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2445)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2501)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2700)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at me.friwi.jcefmaven.impl.step.init.CefInitializer.initialize(CefInitializer.java:57)
	at me.friwi.jcefmaven.CefAppBuilder.build(CefAppBuilder.java:290)
	at me.friwi.jcefsampleapp.MainFrame.<init>(MainFrame.java:82)
	at me.friwi.jcefsampleapp.MainFrame.main(MainFrame.java:197)

This occurs with OpenJDK 11, 17 and 8 (with both the Adoptium binaries as well as the distribution-specific ones) on Rocky Linux 9 installed in a Parallels VM on a MacBook Pro using the M2 processor.

**Comment by S1artie** [comment]
Addition: this exact error also happens on Ubuntu 22.04 LTS in arm64 variant installed on the same MacBook Pro with M2.

**Comment by FriwiDev** [comment]
According to some guys on the internet, the solution could be to preload a library. Can you check wether the library mentioned under this link exists on both your systems?

https://forums.developer.nvidia.com/t/cv2-cannot-allocate-memory-in-static-tls-block/118709

You could also try to test wether it works by preloading the mentioned library. If I need to provide something for you to test, I'm sadly not able to until next week thursday. But maybe you can try preloading in the code before you call jcefmaven.

All the best!

**Comment by S1artie** [comment]
I also stumbled over those suggestions with regard to libgomp. However, CEF does not use libgomp, hence preloading it doesn't work (I tested it). What actually works as kind-of-a-workaround is LD_PRELOADing exactly the libcef.so library which fails to be loaded dynamically!

However, obviously this tactic is not very compatible with the idea of dynamically downloading and/or extracting the JCEF/CEF libraries with the same Java process that later wants to dynamically load them, as setting LD_PRELOAD after starting the process has no effect at all.

It seems as if the Java binary itself, or some JVM dynamic library loaded into it, would somehow make it impossible for libcef to be loaded later, maybe by claiming all the memory possible in that "static TLS block" (I'm not too much into ARM memory management, so my understanding of the background of this issue is very limited right now) and leaving too little for libcef. By turning the loading order around, the JVM still seems to be able to load (maybe it just dynamically allocates less TLS memory because it finds less free now?) and since libcef is already pre-loaded by force, the "dynamic load step" effectively becomes a no-op.

**Comment by ozgurliman** [comment]
The problem can be the Chrome version. 
I faced a similar issue. Using an older maven solved the problem....

**Comment by ozgurliman** [comment]
implementation 'me.friwi:jcefmaven:110.0.25' 
gives the same error
implementation 'me.friwi:jcefmaven:109.1.11'
works.
because of an older chrome version...
It would be perfect if the newer version includes older chrome capability....
Some older pc cannot be upgraded to new chrome versinons..

**Comment by S1artie** [comment]
Didn't work for me. I get the exact same exception when using jcefmaven version 109.1.11.

**Comment by FriwiDev** [comment]
This issue seems to be a general glibc issue. I found more reading on it here: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8225498 I don't think that the proposed jvm flag will solve the issue, but feel free to try it. Maybe preloading the libs in the start command of your java processes would be the easiest fix for now, I don't think that we can do anything about it as of now other than suggesting users to preload on linux/macosx:arm*

**Comment by S1artie** [comment]
Here's another external issue worth monitoring - since JetBrains is using JCEF as well in some of their products, they currently face the same issue: https://youtrack.jetbrains.com/issue/CWM-7461

**Comment by tkggusraqk** [comment]
@FriwiDev The maven dependencies I use package all dependencies into the program
