### ISSUE TITLE
[BUG] Can not run (failed to map segment from shared object)

### ISSUE THREAD

**Issue by TavakoliAli** [jcefmaven/jcefmaven#74]
**Describe the bug**
After download, I get gollowiing error:

```
INFO: EXTRACTING |> In progress...
May 06, 2023 3:02:31 PM me.friwi.jcefmaven.impl.progress.ConsoleProgressHandler handleProgress
INFO: INSTALL |> In progress...
May 06, 2023 3:02:31 PM me.friwi.jcefmaven.impl.progress.ConsoleProgressHandler handleProgress
INFO: INITIALIZING |> In progress...
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/linaro/jcef-bundle/libjcef.so: /home/linaro/jcef-bundle/libjcef.so: failed to map segment from shared object
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2445)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2501)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2700)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at me.friwi.jcefmaven.impl.step.init.CefInitializer.initialize(CefInitializer.java:57)
	at me.friwi.jcefmaven.CefAppBuilder.build(CefAppBuilder.java:233)
	at me.friwi.jcefsampleapp.MainFrame.<init>(MainFrame.java:82)
	at me.friwi.jcefsampleapp.MainFrame.main(MainFrame.java:197)
```

**Environment (please complete the following information):**
 - OS: linux - Debian 10
 - Architecture: aarch64 (amd64)
 - JAVA =
 openjdk 11.0.16 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Debian-1deb10u1, mixed mode)

@FriwiDev

**Comment by FriwiDev** [comment]
Does your home directory have execute permissions?
