### ISSUE TITLE
[BUG] UnsatisfiedLinkError jawt.dll already loaded in another classloader

### ISSUE THREAD

**Issue by ITXalejandrooma** [jcefmaven/jcefmaven#84]
**Describe the bug**
When we try to initialize the browser of the CefAppBuilder.build statement, we encounter the following error:
`java.lang.UnsatisfiedLinkError: Native Library C:\Program Files\Java\jdk1.8.0_251\jre\bin\jawt.dll already loaded in another classloader
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1900)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1838)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1122)
    at com.sun.java.accessibility.AccessBridgeLoader$2.run(AccessBridgeLoader.java:61)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessController.doPrivileged(AccessController.java:429)
    at com.sun.java.accessibility.AccessBridgeLoader.<init>(AccessBridgeLoader.java:58)
    at com.sun.java.accessibility.AccessBridge.<init>(AccessBridge.java:91)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at java.lang.Class.newInstance(Class.java:442)
    at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:805)
    at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
    at java.awt.Toolkit.getEventQueue(Toolkit.java:1736)
    at java.awt.EventQueue.isDispatchThread(EventQueue.java:1071)
    at javax.swing.SwingUtilities.isEventDispatchThread(SwingUtilities.java:1366)
    at org.cef.CefApp.<init>(CefApp.java:167)
    at org.cef.CefApp.getInstance(CefApp.java:221)
    at me.friwi.jcefmaven.impl.step.init.CefInitializer.initialize(CefInitializer.java:76)
    at me.friwi.jcefmaven.CefAppBuilder.build(CefAppBuilder.java:263)
    at com.inditex.facturas.ui.commons.browser.jcef.JCEFBrowserApp.createCefApp(JCEFBrowserApp.java:92)
    at com.inditex.facturas.ui.commons.browser.jcef.JCEFBrowserApp.getCefApp(JCEFBrowserApp.java:51)
    at com.inditex.facturas.ui.commons.browser.jcef.JCEFBrowserApp.getCefApp(JCEFBrowserApp.java:44)
    at com.inditex.facturas.ui.VentanaPrincipal$1.run(VentanaPrincipal.java:181)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at com.inditex.facturas.ui.VentanaPrincipal.main(VentanaPrincipal.java:145)
    at com.inditex.facturas.Main.main(Main.java:29)`

Reviewing possible bugs of this library we saw this: https://github.com/chromiumembedded/java-cef/issues/317
This specifies what was fixed in this commit: https://bitbucket.org/chromiumembedded/java-cef/commits/fbfa9202

In the version of the jcefmaven library that we are using 107.1.9.1, is integrating this commit, but the code is failing later, specifically in this line:
![image](https://github.com/jcefmaven/jcefmaven/assets/96115060/418c26dd-75d1-4c17-b161-aeac046cb56c)

Please, could you tell us what it can be due to and how to solve it?  Thanks in advance

**Environment (please complete the following information):**
 - OS: windows
 - Architecture: i386
 - Version: 107.1.9.1

**Comment by 1fxe** [comment]
You can override the loader in SystemBootstrap before the app is loaded, here's a small example 
```java
SystemBootstrap.setLoader(libname -> {
     if (libname.equals("jawt")) {
         // Do some checking if lib was already loaded maybe check classloader? 
        return;
     }
     System.loadLibrary(libname);
});
```
@ITXalejandrooma
