### ISSUE TITLE
[ENH] cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by xcmonline** [jcefmaven/jcefmaven#96]
OS: ubuntu-20.04  aarch 64
Memory：4G
JDK：17.0.10

Exception in thread "main" java.lang.UnsatisfiedLinkError: /mnt/user/test/jcef-bundle/libjcef.so: /mnt/user/test/jcef-bundle/libcef.so: cannot allocate memory in static TLS block
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1957)
        at me.friwi.jcefmaven.impl.step.init.CefInitializer.initialize(CefInitializer.java:57)
        at me.friwi.jcefmaven.CefAppBuilder.build(CefAppBuilder.java:308)
        at com.onem.frame.cef.OnemBrower.<init>(OnemBrower.java:117)
        at com.onem.frame.cef.OnemBrower.getInstance(OnemBrower.java:53)
        at com.onem.frame.MainFrame.<init>(MainFrame.java:55)
        at com.onem.frame.MainFrame.getInstance(MainFrame.java:37)
        at com.onem.frame.MainFrame.main(MainFrame.java:120)

**Comment by FriwiDev** [comment]
This is a duplicate to #70 - maybe we can discuss further there?
